### PR TITLE
feat: enhance the code

### PR DESCRIPTION
**Pull request by dante4rt**

### CODE REVIEW

**Comment by Zodomo** [comment]
Could you resolve conflicts so I can take an updated look?

**Comment by dante4rt** [comment]
> Could you resolve conflicts so I can take an updated look?

Resolved.

**Comment by Zodomo** [comment]
Could you send me an Ethereum address to send a 404Miya token to it? We unfortunately won't be merging this PR as much has changed since it was submitted, but I still appreciate you nonetheless! If you'd like to take another look and resubmit, feel free!

**Comment by dante4rt** [comment]
> Could you send me an Ethereum address to send a 404Miya token to it? We unfortunately won't be merging this PR as much has changed since it was submitted, but I still appreciate you nonetheless! If you'd like to take another look and resubmit, feel free!

Hi, thank you for your response! I understand about the changes and appreciate the consideration. Could you please let me know where I should send my Ethereum address for the 404Miya token?

**Pull request closed without merging**
